# Git execution command.
bin: git

# Changelog style (github, gitlab, bitbucket, none)
style: github

# Path for the template file
template: CHANGELOG.tpl.md

# Metadata for CHANGELOG
info:
  title: CHANGELOG
  repository_url: https://github.com/dylanljones/lattpy

options:
  sort: "date"

  commits:
     filters:
       Type:
         - feat
         - fix
         - perf
         - refactor
  commit_groups:
     title_maps:
       feat: New Features
       fix: Improvements/Bug Fixes
       perf: Performance Improvements
       refactor: Code Refactoring
  header:
    pattern: "^(\\w*)\\:\\s(.*)$"
    pattern_maps:
      - Type
      - Subject
  notes:
    keywords:
      - BREAKING CHANGE
