name: Generate changelog

on:
  push:
    branches: [master, dev]
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: nuuday/github-changelog-action@v1.0.0
        with:
          filename: CHANGELOG.md
          next_version: "1.0.0"
      - name: Commit files
        run: |
          git config --local user.email "dylanljones94@gmail.com"
          git config --local user.name "dylanljones"
          git add CHANGELOG.md
          git commit -m "auto-update CHANGELOG.md"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: ${{ github.ref }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
