name: Generate changelog

on:
  push:
    branches: [master, dev]
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: nuuday/github-changelog-action@v1.0.0
        with:
          filename: CHANGELOG.md
          next_version: "1.0.0"
      - name: upload
        run: |
          git add CHANGELOG.md
          git commit -m "auto-update CHANGELOG.md"
          git push
